"use client"

import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { AuthProvider } from '../contexts/AuthContext'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>
            <nav className="navbar .bg-dark .text-light">
              <div className="navbar-especial">
                <Link href={"/"}>Oasis</Link>
              </div>
            </nav>
          </div>
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
